"""
Defines the formal grammar and vocabulary for the EchoForm system.

This module serves as the single source of truth for all valid tokens,
operators, and event types that can be parsed and processed by the
Kimera SWM. Centralizing the grammar here ensures system-wide
consistency and makes the language extensible.
"""

# --- Core Event Types ---
# Represents the primary type of event being described.

# A standard event record
ECHOFORM_EVENT = "ECHOFORM_EVENT"

# An insight generated by the Re-Contextualization Engine
INSIGHT_EVENT = "INSIGHT_EVENT"


# --- Insight Sub-Types ---
# Specific categories of insights that can be generated.

ANALOGY = "ANALOGY"
HYPOTHESIS = "HYPOTHESIS"
FRAMEWORK = "FRAMEWORK"
SOLUTION = "SOLUTION"


# --- Core Operators ---
# Standard operators used within EchoForm expressions.

QUOTE = "quote"
SET = "set"
IF = "if"


# --- Vocabulary Sets ---
# Collections of tokens for validation purposes.

CORE_EVENT_TYPES = {
    ECHOFORM_EVENT,
    INSIGHT_EVENT,
}

INSIGHT_SUB_TYPES = {
    ANALOGY,
    HYPOTHESIS,
    FRAMEWORK,
    SOLUTION,
}

CORE_OPERATORS = {
    QUOTE,
    SET,
    IF,
}

# The complete vocabulary for validation by the parser or other engines.
ECHOFORM_VOCABULARY = CORE_EVENT_TYPES | INSIGHT_SUB_TYPES | CORE_OPERATORS 